name: Trigger auto deployment for test1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test1-AutoDeployTrigger-52128d14-2aed-464c-a356-392dd5241f9a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEST1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TEST1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST1_REGISTRY_PASSWORD }}
          containerAppName: test1
          resourceGroup: op-rg-ambamonitoring-sc-shared-01
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


